### ISSUE TITLE
Homepage - Get In Touch : Form should not hit the section border when title text is removed.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Beyond-Voice-Radio#28]
![28](https://cloud.githubusercontent.com/assets/18256652/16375706/4437f0a8-3c8f-11e6-9ace-883307b5e805.png)

**Comment by iteano** [comment]
Cannot verify this issue since Get In Touch text on homepage was hard coded currently, please make it dynamic.

![image](https://cloud.githubusercontent.com/assets/18256652/16646731/53e314b6-445e-11e6-8671-b637e9fde52d.png)

**Comment by henrytitan** [comment]
The Title is located in the sidebar area widget as it is stated in the project scope.
